name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      # Skip cache temporarily to ensure fresh install
      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v3
      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-scripts --no-progress
      - name: List Vendor Bin Directory
        run: ls -la vendor/bin
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite
      - name: Run PHPUnit Tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: vendor/bin/phpunit || ./vendor/phpunit/phpunit/phpunit
